version: "3.9"

services:
  discord-slack-forwarder:
    build: ./discord-slack-forwarder/
    container_name: discord-slack-bot
    restart: unless-stopped
    environment:
      # ⚠️ トークンやWebhook URLは必ず環境変数で管理！
      DISCORD_BOT_TOKEN: ${DISCORD_BOT_TOKEN}
      SLACK_WEBHOOK_URL_NEW_TWEETS: ${SLACK_WEBHOOK_URL_NEW_TWEETS}
      # TARGET_DISCORD_CHANNEL_ID_NEW_TWEETS: ${TARGET_DISCORD_CHANNEL_ID_NEW_TWEETS}
      SEARCH_KEYWORDS_NEW_TWEETS: ${SEARCH_KEYWORDS_NEW_TWEETS}
    volumes:
      - ./discord-slack-forwarder:/usr/src/app
    command: ["python", "bot.py"]
